# Generated by Django 5.1.6 on 2026-09-11 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late')], max_length=20)),
            ],
            options={
                'ordering': ['-attendance_date', '-clock_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=40, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('employee', 'Employee / Staff'), ('admin', 'Administrator')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_no'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_resumption', models.TimeField(default='08:00')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Clocking setting',
                'verbose_name_plural': 'Clocking settings',
            },
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='uploads.employee'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='one_attendance_per_employee_day'),
        ),
    ]
