# Generated by Django 5.1.6 on 2026-09-11 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_attendance_employee_systemsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='official_resumption',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
