# Generated by Django 5.2.17 on 2026-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_systemsetting_official_resumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_face',
            field=models.FileField(blank=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_face',
            field=models.FileField(blank=True, upload_to='attendance_faces/'),
        ),
    ]
